Matthias247/futures-intrusive

benches/mpmc_channel.rs, examples/philosophers.rs, src/lib.rs, tests/manual_reset_event.rs, tests/mpmc_channel.rs, tests/mutex.rs, tests/oneshot_channel.rs, tests/semaphore.rs, tests/state_broadcast_channel.rs, tests/timer.rs
async_await is now stable, but async closures are on a separate feature
now.
=> Fix up features

src/channel/channel_future.rs, src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, src/channel/state_broadcast.rs, tests/mpmc_channel.rs, tests/oneshot_channel.rs, tests/state_broadcast_channel.rs
Previous versions of the library couldn't be used with multithreaded
runtimes because the Futures haven't been marked as Send - even though
they technically were (had been synchronized by thread-safe mutexes).
Since however not all channels are thread-safe (LocalChannels are not)
it is not possible it is not possible to add the Send attribute to all
Future types. Therefore this change parameterizes the returned Futures
by the Mutex type and makes Futures only Sendable if a thread-safe
(Sync) mutex is used.
This implementation preferred to leak only the Mutex type into the
returned Future, and not the underlying channel type. This has the
advantage of a little bit less type leaks.
=> Make channel futures Send

src/lib.rs
In this commit, we fix some grammatical errors and improve the fluency
and clarity of the top-level crate documentation in `src/lib.rs`.  No
meaning was changed, and no substance was added or removed.  This is
just a rewording.
=> Fix/improve top-level documentation wording

src/buffer/mod.rs, src/buffer/ring_buffer.rs, src/channel/mpmc.rs
This allows user to have channel whose capacity grows over time
up to a certain limit.
This is a breaking change. Maybe defaulting the generic `RingBuf` parameter to `HeapRingBuf` would make it not breaking, but i'm not sure that's wise.
On a side note, I kinda feel like the `RingBuf` trait `capacity` term is confusing because when the term is used in the std lib it implies that it is growable. For instance in this specific PR the `capacity` (as in elements limit) of the `GrowingRingBuf` is fixed yet the `capacity` (as in allocated mem) grows as needed. I think it should be renamed to something more fitting like `limit` or `max_size` to avoid confusion.
Fixes #15.
=> Added GrowingRingBuf implementation

src/channel/channel_future.rs, src/channel/error.rs, src/channel/mod.rs, src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, tests/mpmc_channel.rs
This allows a user to attempt to send & recv without blocking.
Had to rename the methods of the ChannelSendAccess &
ChannelReceiveAccess.
Btw why use `receive` instead of `recv`?
Also I should be back on working on #12 very soon (maybe after this weekend).
=> Added try_send and try_receive methods

benches/mpmc_channel.rs, src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, src/channel/state_broadcast.rs, src/lib.rs, src/sync/manual_reset_event.rs, src/sync/mutex.rs, src/sync/semaphore.rs, src/timer/timer.rs, src/utils/mod.rs, tests/manual_reset_event.rs, tests/mpmc_channel.rs, tests/mutex.rs, tests/oneshot_channel.rs, tests/semaphore.rs, tests/state_broadcast_channel.rs, tests/timer.rs
If Futures are polled multiple times while not being able to make
progress, we need to update the stored Waker. It is allowed to pass
a different Waker to each poll call, and we should make sure to store
the last Waker in order to properly unblock tasks.
Fixes #18
=> Update stored Wakers if polled again

src/channel/state_broadcast.rs
Only affects `state_broadcast.rs` for no_std.
=> Import `PhantomData` from `core` instead of `std`

src/channel/mpmc.rs, tests/mpmc_channel.rs
This method returns a type which implements Future::Stream.
=> WIP: Add stream method to channel

src/channel/mod.rs, src/channel/mpmc.rs, tests/mpmc_channel.rs
The Channel::close method now returns `PrevState`, which
represents the previous state of the channel prior to being
closed.
This closes #25.
=> Updated mpmc Channel::close method signature

src/channel/channel_future.rs, src/channel/mod.rs, src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, src/channel/state_broadcast.rs, tests/oneshot_channel.rs, tests/state_broadcast_channel.rs
Oneshot & broadcast channels now return `CloseStatus` when
`close` is called, which allows the user to know if the
channel was already closed.
This is a continuation of #26 for the remaining channel implementations.
=> Updated {Oneshot,Broadcast}Channel::close signature

src/channel/state_broadcast.rs, tests/state_broadcast_channel.rs
This is useful when you want to check synchronously if you received a new update.
Normally you would do this via `receiver.receive(StateId::new()).await` and then check if the `StateId` is greater than the previous, but this might block if there is no value in the channel.
=> Added try_receive method to state broadcast channel

src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, src/channel/state_broadcast.rs, src/intrusive_double_linked_list.rs, src/sync/manual_reset_event.rs, src/sync/mutex.rs, src/sync/semaphore.rs, src/timer/timer.rs
This is an attempt to reduce the amount of unsafe code and
raw pointers in intrusive list usage.
The main unsafe function is now adding a node to the intrusive linked
list, which requires the caller to assure they will remove the item
properly later on.
Many other functions have been converted to safe functions. In order for
the iterators to be safe, they had been converted to internal iterators.
External iterators did not provide proper guarantees on when they will
drain the list.
The change also moved from raw pointers to using
`Option<NonNull<ListNode<T>>>` for intrusive list
=> Refactor the intrusive linked list

src/channel/channel_future.rs, tests/mpmc_channel.rs
This adds the ability to call cancel on the shared version of `ChannelSendFuture`.
I added some tests similar to the non-shared channel.
=> Added cancel method for the shared ChanncelSendFuture version

src/intrusive_double_linked_list.rs, src/intrusive_pairing_heap.rs, src/lib.rs, src/timer/timer.rs
This makes the timer more efficient when it has many nodes (O(1) rather
than O(n) insertion, and amortized O(log n) removal).
=> Implement TimerService with an intrusive pairing heap.

src/channel/mpmc.rs, tests/mpmc_channel.rs
This allows the content of the channel to be dropped even if all the senders are not dropped.
My specific use case is that I have a `Handle` held by a user that contains a `Sender<OneshotSender>` that is sent to the `Driver` that hold the `Receiver<OneshotSender>`. Let's say the `Driver` errors and is dropped, then the `OneshotSender` will never be dropped unless the user drops the `Handle`, which can't be forced. If the user also hold some kind of future that waits on the `OneshotSender`, this creates a deadlock.
=> Dropping the last GenericReceiver now clears the channel

src/channel/mpmc.rs, tests/mpmc_channel.rs
This allow the user to close the channel via the stream.
Note that I had to add the `is_terminating` field so that the `close` method still works even if the stream is terminated.
=> Add SharedStream::close method

src/channel/mod.rs
The `channel::mpmc::ChannelStream` type is returned by `channel::GenericChannel::stream`, but the type wasn't exposed so the return type couldn't be named. This exposes it from `channel`.
Signed-off-by: Vivian Hellyer <vivian@hellyer.dev>
=> Expose channel::ChannelStream

src/sync/mod.rs, src/sync/semaphore.rs, tests/semaphore.rs
This adds a shared generic semaphore implementation that can be shared across threads or futures.
My use case is a set of future ran concurrently in an executor that are each rate-limited via a shared semaphore.
=> Add shared semaphore implementation

src/sync/mutex.rs
I thought of fixing this by tossing in a `PhantomData` so that it would be valid when `T` is `Sync` but I don't think that's good since the `UnsafeCell` would still be accessed across threads. I thus ended up setting the trait `!Sync` like the nomicon suggests: https://doc.rust-lang.org/beta/nomicon/send-and-sync.html
I don't think this needs a test though theoretically this is possible, see https://users.rust-lang.org/t/a-macro-to-assert-that-a-type-does-not-implement-trait-bounds/31179.
=> Add a Sync bound for GenericMutexGuard.. Fixes #53.

.travis.yml, Cargo.toml, src/channel/mod.rs, src/channel/mpmc.rs, src/channel/oneshot.rs, src/channel/oneshot_broadcast.rs, src/channel/state_broadcast.rs, src/sync/manual_reset_event.rs, src/sync/mod.rs, src/sync/mutex.rs, src/sync/semaphore.rs, src/timer/clock.rs, src/timer/mod.rs, src/timer/timer.rs, tests/mpmc_channel.rs, tests/oneshot_channel.rs, tests/semaphore.rs, tests/state_broadcast_channel.rs, tests/timer.rs
Currently you cannot build `alloc` version of the crate in `no_std` environment because `alloc` feature imports `parking_lot`. This PR decouples predefined `parking_lot` types and allows generic types to be used in `no_std` environment (with your own `RawMutex` implementation).
=> Decouple alloc from std

src/intrusive_double_linked_list.rs, src/sync/mutex.rs, src/sync/semaphore.rs
I noticed a soundness issue while looking through the `LinkedList` implementation. Since `peek_first` and `peek_last` took a shared reference but returned a mutable reference to the `ListNode` it would be trivial to create multiple mutable references to the same `ListNode` which is UB, even from safe code:
```rust
let mut a = ListNode::new(5);
let mut list = LinkedList::new();
unsafe {
list.add_front(&mut a);
}
let a1 = list.peek_first().unwrap();
let a2 = list.peek_first().unwrap();
assert_eq!(a1 as *mut _, a2 as *mut _); // Undefined behavior
```
The good news is that the actual uses of `LinkedList` in the crate do not trigger that UB.
This PR fixes the problem by making `peek_first` and `peek_last` return shared references and adding `peek_first_mut` and `peek_last_mut` which take …
=> Fix LinkedList unsoundness
